apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
      version: "1.11.0"
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 10m0s
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      storageReservedPercentageForDefaultDisk: 15
      defaultLonghornStaticStorageClass: "longhorn-ssd"
    defaultBackupStore:
      backupTarget: "azblob://longhorn-backups@core.windows.net/"
      backupTargetCredentialSecret: "longhorn-backup-secret"
    persistence:
      defaultClass: false

