---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      version: 1.92.5
  interval: 1h0m0s

  install:
    crds: CreateReplace
    remediation:
      retries: 3

  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    oauth:
      clientId: ""
      clientSecret: ""
      
    oauthSecretVolume:
          secret:
            secretName: tailscale-oauth-secret 
            items:
              - key: client-id
                path: client_id
              - key: client-secret
                path: client_secret