apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  interval: 1h0m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      # Usiamo una versione stabile recente
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 1h
  
  install:
    createNamespace: true
    remediation:
      retries: 3

  values:
    provider: cloudflare
    policy: sync
    sources:
      - ingress
      - service
    domainFilters:
      - dariomazza.net
    
    txtOwnerId: "k8s-homelab"
    
    cloudflare:
      proxied: false
      
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: token
