apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-github-secret
  namespace: glance
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: glance-github-secret
    creationPolicy: Owner
  data:
  - secretKey: GITHUB_TOKEN
    remoteRef:
      key: github-token
