apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-steam-secret
  namespace: glance
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: glance-steam-secret
    creationPolicy: Owner
  data:
  - secretKey: STEAM_API_KEY
    remoteRef:
      key: steam-api-key
