apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ingress-nginx
      version: "4.14.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-layer2: "true"
      
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      
      metrics:
        enabled: true
      
      admissionWebhooks:
        enabled: false
