---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: private-homelab      
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/xDaryamo/private-homelab.git
  ref:
    branch: master
  secretRef:
    name: private-homelab

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-apps        
  namespace: flux-system
spec:
  interval: 10m
  path: "./production"
  prune: true     
  wait: true
  sourceRef:
    kind: GitRepository
    name: private-homelab  
  decryption:
    provider: sops
    secretRef:
      name: sops-age 