apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: vocard
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: vocard-mongodb
      property: username
  - secretKey: password
    remoteRef:
      key: vocard-mongodb
      property: password
