apiVersion: v1
kind: Service
metadata:
  labels:
    app: hyperion
  name: hyperion
spec:
  ports:
  - name: web-ui
    port: 8090
    protocol: TCP
    targetPort: 8090
  - name: json-api
    port: 19444
    protocol: TCP
    targetPort: 19444
  - name: proto-grabber
    port: 19445
    protocol: TCP
    targetPort: 19445
  - name: flat-buffer
    port: 19400
    protocol: TCP
    targetPort: 19400
  selector:
    app: hyperion
  type: LoadBalancer
