apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/podinfo

namespace: podinfo-staging

patches:
  - target:
      kind: HelmRelease
      name: podinfo
    patch: |-
      - op: add
        path: /spec/values/ui/message
        value: "Hello from staging!"
