apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      containers:
        - name: podinfo
          env:
            - name: PODINFO_UI_MESSAGE
              value: "🚧 Warning: Staging Environment 🚧"
            - name: PODINFO_UI_COLOR
              value: "#34577c"
