apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.6"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  targetNamespace: kube-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    mtu: 1280
    kubeProxyReplacement: true

    l2announcements:
      enabled: true
    externalIPs:
      enabled: true

    ipam:
      mode: "kubernetes"

    operator:
      replicas: 1

    devices: "enp0s31f6"
