apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-storage
  labels:
    recurring-job-group.longhorn.io/critical-data: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-ssd
