apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: subito-searcher
resources:
  - ../../base/subito-searcher
  - namespace.yaml
  - telegram-secret.yaml
configMapGenerator:
  - name: subito-searcher-queries
    files:
      - queries.yaml
