apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: subito-searcher-telegram
  namespace: subito-searcher
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: subito-searcher-telegram
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: subito-searcher-telegram
        property: TELEGRAM_BOT_TOKEN
    - secretKey: TELEGRAM_CHAT_ID
      remoteRef:
        key: subito-searcher-telegram
        property: TELEGRAM_CHAT_ID
