apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant
  annotations:
    lbipam.cilium.io/ips: "192.168.1.205"   # must match emulated_hue advertise_ip
spec:
  ports:
  - name: hue
    port: 80
    protocol: TCP
    targetPort: 80
  - name: web-ui
    port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: home-assistant
  type: LoadBalancer
