---
- name: Build K3s Cluster
  hosts: k3s_cluster # parent group
  gather_facts: true
  become: true #sudo

  pre_tasks:
    - name: Set Control Plane Variable
      set_fact:
        k3s_control_node: true
      when: "'control_plane' in group_names"

    - name: Set Worker Variable
      set_fact:
        k3s_control_node: false
      when: "'workers' in group_names"

  vars:
    k3s_become: true

    k3s_release_version: "v1.34.2+k3s1"

    k3s_registration_address: "192.168.1.24"

    k3s_server:
      # Disabling the default components, we'll use Flux to install better alternatives
      disable:
        - traefik
        - servicelb

      # Since PC 1 has 16GB of RAM, it would be a waste not to use it for the apps!
      node-taint: []

    k3s_agent: {}

  roles:
    - role: xanmanning.k3s
