apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:EaJWNCIj2Telc6xk3zgvuqwlv5qwTNgF0Np66KY+afmk6KF0PMVcELK2zKKDG22etTCUTZ+IVzGWm84REkj1WxVJWXTTxgzmLyGBZb6yvl5YggK3BjWvahrPOGIm0gtvLedk4OSjoYuKBeo9J2XWg4eQchTXVOCG/sZJbhZRLlHskhIYj4w43Qm2etxw0U9Evbar7oYD5BzHz5jKP0ybC17SB/otWR2DOTYm5mNdWUm33ALwozAkx9KtCuYglZM5XFfy7b5ILcVJpoMo+inMU75NeHusBASdZpq4yb7xK+12/y1LrlXPO5JwsG6bJf4WitX08a6z9rc=,iv:7IDmMIjvD4E5VEmjdJgF8LxC2mllH9AtJBxZfWCs8WM=,tag:lM7GxrijiO5l91dyk7SZIg==,type:str]
kind: Secret
metadata:
    name: cloudflared-token-secret
sops:
    age:
        - recipient: age1hj9gxc8xjg96lpjqk29ay98zsy3j9j7lxygpj4hgfh85vpmd35rstj5qzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY3J5WTFyRXhLd0wyYVVm
            TDR4a2xkZ2tuSGhkazBzTzdsS2hDL3lxeWtBCkhXZmUwVDAvcEdDUW5NK1FnTE1p
            eEJBNmxZbnhrdm16THNZdHZKVVdUczgKLS0tIHIyZWFhVWtINEs4Y2JDMnUzLzRS
            Q1kzRlg4cklYSzFNd3J5TVBEYlhYbk0KBy9Og4Hlb9PFm8OyrFn+2KrULUuKNWu4
            NAxYlX2+vfZUYYfEgX65n4VVcVPt+P+0TMYMI6/8rw5eAJcE7dnapw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T11:14:33Z"
    mac: ENC[AES256_GCM,data:3CT2YyyFFGxgP1fKwKl/oUuP7YkixPtIzWIk1PSdT7vcZ9CbT1/KjdquoEA2kVM8gI4Tx1S51ewulGm/6/1Zhc9BIn2TyGe1sSY+YNHSfc4iqXFIp65TEKXhPK02+fFlptkrxotm5q094WTJLZVuPJyq+ztZ5GwS3uRF9/ci904=,iv:u/5WNFNzKSUrATiJUmOie2HQRABHjx3tUy9EnGFNG2I=,tag:ZRl8c0wY7AvWG7OiU1/GKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
