apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: cloudflared 
        namespace: cloudflared
  interval: 1h0m0s
  values:
    env:
      - name: TUNNEL_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflared-token-secret
            key: TUNNEL_TOKEN