apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  chart:
    spec:
      chart: cloudflare-tunnel
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudflared
        namespace: cloudflared
      version: 0.3.2

  interval: 1h0m0s

  values:
    env:
      - name: TUNNEL_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflared-token-secret
            key: TUNNEL_TOKEN

    cloudflare:
      secretName: cloudflared-token-secret
      tunnelName: k8s-homelab
      ingress:
        - hostname: "*.dariomazza.net"
          service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
        - hostname: "dariomazza.net"
          service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
        - service: http_status:404

