apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocard
  labels:
    app: vocard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vocard
  template:
    metadata:
      labels:
        app: vocard
    spec:
      initContainers:
        - name: init-config
          image: busybox:latest
          command: ["sh", "-c", "cp /config-vocard/settings.json /app-vocard/settings.json && cp /config-lavalink/application.yml /app-lavalink/application.yml"]
          volumeMounts:
            - name: settings-secret
              mountPath: /config-vocard
            - name: settings-volume
              mountPath: /app-vocard
            - name: lavalink-config-secret
              mountPath: /config-lavalink
            - name: lavalink-config-volume
              mountPath: /app-lavalink
      containers:
        - name: vocard
          image: ghcr.io/chocomeow/vocard:beta
          command: ["sh", "-c", "until python3 -c 'import socket; s = socket.socket(); s.connect((\"127.0.0.1\", 2333))' 2>/dev/null; do echo 'Waiting for Lavalink...'; sleep 1; done; python3 main.py"]
          volumeMounts:
            - name: settings-volume
              mountPath: /app/settings.json
              subPath: settings.json
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"

        - name: lavalink
          image: ghcr.io/lavalink-devs/lavalink:4.2.1
          env:
            - name: _JAVA_OPTIONS
              value: "-Xmx1G"
            - name: SERVER_PORT
              value: "2333"
          ports:
            - containerPort: 2333
              name: http
          volumeMounts:
            - name: lavalink-config-volume
              mountPath: /opt/Lavalink/application.yml
              subPath: application.yml
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 2333
            initialDelaySeconds: 20
            periodSeconds: 10

        - name: spotify-tokener
          image: ghcr.io/topi314/spotify-tokener:master
          env:
            - name: SPOTIFY_TOKENER_ADDR
              value: "0.0.0.0:49152"
          ports:
            - containerPort: 49152
              name: tokener
          livenessProbe:
            tcpSocket:
              port: 49152
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: settings-secret
          secret:
            secretName: vocard-settings
        - name: settings-volume
          emptyDir: {}
        - name: lavalink-config-secret
          secret:
            secretName: lavalink-config
        - name: lavalink-config-volume
          emptyDir: {}
