apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  releaseName: gitlab
  chart:
    spec:
      chart: gitlab
      version: ">= 7.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  interval: 1h
  values:
    global:
      hosts:
        domain: dariomazza.net
        gitlab:
          name: gitlab.dariomazza.net
        registry:
          name: registry.dariomazza.net
        kas:
          name: kas.dariomazza.net
      ingress:
        configureCertmanager: true
        class: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/tls-acme: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "e859d444-74bb-4e45-8426-1e6141995ed9.cfargotunnel.com"
      appConfig:
        signupEnabled: false
      kas:
        enabled: true
      prometheus:
        install: false
      certmanager:
        install: false
      nginx-ingress:
        enabled: false
      minio:
        enabled: true
    
    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 2
      sidekiq:
        replicas: 1
      kas:
        enabled: true
      gitaly:
        persistence:
          size: 20Gi
          storageClass: longhorn

    registry:
      enabled: true
      persistence:
        size: 20Gi
        storageClass: longhorn

    minio:
      persistence:
        size: 10Gi
        storageClass: longhorn

    postgresql:
      install: true
      primary:
        extendedConfiguration: |
          max_connections = 200
        persistence:
          size: 10Gi
          storageClass: longhorn

    redis:
      install: true
      master:
        persistence:
          size: 5Gi
          storageClass: longhorn

    gitlab-runner:
      install: true
      rbac:
        create: true
      hostAliases:
        - ip: "192.168.1.200"
          hostnames:
            - "registry.dariomazza.net"
            - "gitlab.dariomazza.net"
      runners:
        privileged: true
        config: |
          [[runners]]
            [runners.kubernetes]
              image = "ubuntu:22.04"
              privileged = true
              [[runners.kubernetes.host_aliases]]
                ip = "192.168.1.200"
                hostnames = ["registry.dariomazza.net", "gitlab.dariomazza.net"]
    certmanager-issuer:
      email: mr.dario.mazza@gmail.com
