apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-webide-extension-host
  namespace: gitlab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: "e859d444-74bb-4e45-8426-1e6141995ed9.cfargotunnel.com"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.gitlab-ide.dariomazza.net"
      secretName: gitlab-webide-tls
  rules:
    - host: "*.gitlab-ide.dariomazza.net"
      http:
        paths:
          - path: /assets/
            pathType: Prefix
            backend:
              service:
                name: gitlab-webservice-default
                port:
                  number: 8181
